"""Evidence dossier PDF — VAYU's unit of output (PRD C2).

Everything upstream converges here. The forecast, the back-trajectory, the fire
detections, the plume counterfactual and the GRAP clause all exist so that this
one page can be handed to an inspector who was not in the room. It must stand on
its own: where to go, what was seen, under what authority, what it should
achieve, and who signed it.

Renderer choice — a documented deviation from TRD 5.6, which prefers WeasyPrint
with a reportlab fallback. WeasyPrint needs native glib/Pango/Cairo, which are
absent on a clean macOS without Homebrew and raise OSError at import. A dossier
that cannot render is a demo with no product, so the sanctioned fallback is the
primary path here. reportlab is pure Python and imports clean.

The map is a schematic locator drawn from ward geometry, not satellite imagery —
labelled as such on the page so nobody mistakes it for a basemap. It carries what
an inspector needs (source pin, ward, wind vector, scale) and needs no network at
dispatch time.
"""

from __future__ import annotations

import io
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

import matplotlib
import numpy as np
import pandas as pd

matplotlib.use("Agg")
import json

import matplotlib.pyplot as plt
from loguru import logger
from reportlab.lib import colors
from reportlab.pdfgen import canvas as canvas_mod
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from vayu_core.config import REPO_ROOT, CityConfig, get_settings
from vayu_core.geo import haversine_km
from vayu_core.interventions.roi import ACTION_LABEL, Candidate

DOSSIER_DIR = REPO_ROOT / "data" / "dossiers"

# This prototype must never be mistaken for a real enforcement order. The
# watermark is on every page, and the disclaimer block is not optional.
WATERMARK = "PROTOTYPE — not an official document"
DISCLAIMER = (
    "This document was generated by VAYU, a prototype decision-support system. "
    "It is <b>not an official order</b> and carries no legal "
    "force. Regulation text is an abridged restatement for demonstration and must be "
    "verified against the current CAQM order before any enforcement action. Predicted "
    "impact comes from a Gaussian plume model with stated confidence, not a measurement."
)

INK = colors.HexColor("#0F172A")
MUTED = colors.HexColor("#64748B")
LINE = colors.HexColor("#E2E8F0")
ACCENT = colors.HexColor("#0EA5E9")
WARN = colors.HexColor("#B45309")


@dataclass
class Dossier:
    order_id: str
    path: Path
    generated_ts: datetime


# ---------------------------------------------------------------------------
# map snapshot
# ---------------------------------------------------------------------------

def _ward_polygon(geom_geojson: str | None) -> list[np.ndarray]:
    """Exterior rings from a GeoJSON Polygon/MultiPolygon string."""
    if not geom_geojson:
        return []
    try:
        g = json.loads(geom_geojson)
    except (json.JSONDecodeError, TypeError):
        return []
    t = g.get("type")
    if t == "Polygon":
        polys = [g["coordinates"]]
    elif t == "MultiPolygon":
        polys = g["coordinates"]
    else:
        return []
    return [np.asarray(p[0], dtype=float) for p in polys if p and p[0]]


def render_map(
    candidate: Candidate,
    ward_geom: str | None,
    rec_lat: float,
    rec_lon: float,
    wind_dir_from_deg: float | None = None,
) -> bytes:
    """Schematic locator: source, affected ward, wind vector, scale bar.

    Drawn offline from ward geometry so a dispatch never blocks on a tile
    server. Deliberately labelled a schematic — it is not imagery.
    """
    fig, ax = plt.subplots(figsize=(7.0, 4.2), dpi=150)

    lats = [candidate.source_lat, rec_lat]
    lons = [candidate.source_lon, rec_lon]

    for ring in _ward_polygon(ward_geom):
        ax.fill(ring[:, 0], ring[:, 1], facecolor="#BAE6FD", edgecolor="#0369A1",
                linewidth=1.2, alpha=0.45, zorder=1)
        lons += list(ring[:, 0])
        lats += list(ring[:, 1])

    # Evidence pixels — the raw detections behind the claim.
    ev_pts = [(e.lon, e.lat) for e in candidate.evidence if getattr(e, "lat", None)]
    if ev_pts:
        ex, ey = zip(*ev_pts)
        ev_label = ("Satellite detections"
                    if all(e.type == "fire" for e in candidate.evidence if getattr(e, "lat", None))
                    else "Evidence")
        ax.scatter(ex, ey, s=26, c="#F97316", marker="s", edgecolors="#7C2D12",
                   linewidths=0.5, zorder=4, label=ev_label)
        lons += list(ex)
        lats += list(ey)

    # Padding: never let a tight cluster zoom to absurd scale.
    pad = max(0.04, (max(lats) - min(lats)) * 0.25, (max(lons) - min(lons)) * 0.25)
    x0, x1 = min(lons) - pad, max(lons) + pad
    y0, y1 = min(lats) - pad, max(lats) + pad

    ax.plot([candidate.source_lon, rec_lon], [candidate.source_lat, rec_lat],
            ls="--", lw=1.2, color=MUTED.hexval().replace("0x", "#")[:7], zorder=2)

    ax.scatter([rec_lon], [rec_lat], s=150, c="#0EA5E9", marker="o",
               edgecolors="white", linewidths=1.5, zorder=5, label="Affected ward")
    ax.scatter([candidate.source_lon], [candidate.source_lat], s=230, c="#DC2626",
               marker="*", edgecolors="white", linewidths=1.0, zorder=6, label="Enforcement target")

    # Wind vector: points the way the air travels (from -> to).
    if wind_dir_from_deg is not None and np.isfinite(wind_dir_from_deg):
        to_deg = (float(wind_dir_from_deg) + 180.0) % 360.0
        theta = np.deg2rad(to_deg)
        dx, dy = np.sin(theta), np.cos(theta)
        L = (x1 - x0) * 0.13
        ax.arrow(x0 + (x1 - x0) * 0.09, y1 - (y1 - y0) * 0.13, dx * L, dy * L,
                 head_width=L * 0.32, head_length=L * 0.32, fc="#334155", ec="#334155", zorder=7)
        ax.text(x0 + (x1 - x0) * 0.09, y1 - (y1 - y0) * 0.06,
                f"wind {int(wind_dir_from_deg)}°", fontsize=7, color="#334155")

    # Scale bar — an inspector needs to read distance off the page.
    km_per_deg_lon = haversine_km(rec_lat, rec_lon, rec_lat, rec_lon + 1.0)
    if km_per_deg_lon > 0:
        target_km = max(5.0, round((x1 - x0) * km_per_deg_lon / 4 / 5) * 5)
        bar = target_km / km_per_deg_lon
        bx, by = x0 + (x1 - x0) * 0.06, y0 + (y1 - y0) * 0.08
        ax.plot([bx, bx + bar], [by, by], lw=2.5, color=INK.hexval().replace("0x", "#")[:7])
        ax.text(bx + bar / 2, by + (y1 - y0) * 0.02, f"{target_km:.0f} km",
                fontsize=7, ha="center", color="#0F172A")

    ax.set_xlim(x0, x1)
    ax.set_ylim(y0, y1)
    # Keep degrees square-ish at this latitude so distances aren't visually skewed.
    ax.set_aspect(1.0 / np.cos(np.deg2rad(rec_lat)))
    ax.set_xticks([])
    ax.set_yticks([])
    for s in ax.spines.values():
        s.set_color("#CBD5E1")
    ax.legend(loc="lower right", fontsize=6.5, framealpha=0.9)
    ax.set_title("Schematic locator — not to-scale imagery", fontsize=7, color="#64748B", loc="left")

    buf = io.BytesIO()
    fig.tight_layout(pad=0.4)
    fig.savefig(buf, format="png", bbox_inches="tight")
    plt.close(fig)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# page furniture
# ---------------------------------------------------------------------------

class _WatermarkCanvas(canvas_mod.Canvas):
    """Stamps PROTOTYPE over the finished page.

    ReportLab's onPage hooks fire *before* the flowables are laid down, so a
    watermark drawn there ends up underneath every opaque table and image — it
    survived only in the whitespace at the bottom of the last page, which is
    exactly where nobody looks. Overriding showPage() puts it on top of the
    content, which is the whole point of a watermark on a document that must
    never be mistaken for a real enforcement order.
    """

    def showPage(self):
        self.saveState()
        self.setFont("Helvetica-Bold", 46)
        self.setFillColor(colors.Color(0.45, 0.50, 0.60, alpha=0.16))
        self.translate(A4[0] / 2, A4[1] / 2)
        self.rotate(38)
        self.drawCentredString(0, 0, "PROTOTYPE")
        self.restoreState()
        super().showPage()


def _watermark(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(MUTED)
    canvas.drawString(18 * mm, 10 * mm, WATERMARK)
    canvas.drawRightString(A4[0] - 18 * mm, 10 * mm, f"Page {doc.page}")
    canvas.setStrokeColor(LINE)
    canvas.line(18 * mm, 13 * mm, A4[0] - 18 * mm, 13 * mm)
    canvas.restoreState()


def _styles() -> dict:
    s = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("t", parent=s["Title"], fontSize=17, leading=21,
                                textColor=INK, spaceAfter=2),
        "sub": ParagraphStyle("s", parent=s["Normal"], fontSize=8.5, textColor=MUTED),
        "h2": ParagraphStyle("h2", parent=s["Heading2"], fontSize=10.5, leading=13,
                             textColor=INK, spaceBefore=9, spaceAfter=4),
        "body": ParagraphStyle("b", parent=s["Normal"], fontSize=8.5, leading=11.5, textColor=INK),
        "small": ParagraphStyle("sm", parent=s["Normal"], fontSize=7.2, leading=9.5, textColor=MUTED),
        "cell": ParagraphStyle("c", parent=s["Normal"], fontSize=7.4, leading=9.2),
        "quote": ParagraphStyle("q", parent=s["Normal"], fontSize=8.2, leading=11,
                                leftIndent=8, textColor=INK),
        "warn": ParagraphStyle("w", parent=s["Normal"], fontSize=7.4, leading=9.6, textColor=WARN),
        "center": ParagraphStyle("ct", parent=s["Normal"], fontSize=7.5, alignment=TA_CENTER,
                                 textColor=MUTED),
    }


def _kv_table(rows: list[tuple[str, str]], st: dict, width: float) -> Table:
    data = [[Paragraph(f"<font color='#64748B'>{k}</font>", st["cell"]),
             Paragraph(v, st["cell"])] for k, v in rows]
    t = Table(data, colWidths=[width * 0.32, width * 0.68])
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LINEBELOW", (0, 0), (-1, -2), 0.4, LINE),
    ]))
    return t


# ---------------------------------------------------------------------------
# the dossier
# ---------------------------------------------------------------------------

def generate(
    candidate: Candidate,
    city: CityConfig,
    ward_geom: str | None,
    rec_lat: float,
    rec_lon: float,
    signal_ts: datetime | None = None,
    wind_dir_from_deg: float | None = None,
    forecast_note: str | None = None,
    out_dir: Path | None = None,
) -> Dossier:
    """Render the dossier for one candidate. Returns the saved path."""
    out_dir = out_dir or DOSSIER_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{candidate.id}.pdf"
    # Use the application clock, not the wall clock. In demo mode "now" is the
    # replayed instant, and mixing the two turned the PRD E2 signal->dossier
    # stopwatch into "368840m 7s" — 256 days — because the signal came from the
    # demo timeline and the generation stamp came from today.
    now = pd.Timestamp(get_settings().now())
    local = now.tz_convert(city.timezone)

    st = _styles()
    doc = SimpleDocTemplate(
        str(path), pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm, topMargin=15 * mm, bottomMargin=16 * mm,
        title=f"VAYU Intervention Order {candidate.id}",
        author="VAYU (prototype)",
        subject=f"{ACTION_LABEL.get(candidate.action_type, candidate.action_type)} — {candidate.ward_name}",
    )
    W = doc.width
    flow = []

    # --- header ---
    flow.append(Paragraph("VAYU · Intervention Order", st["title"]))
    flow.append(Paragraph(
        f"{candidate.id} &nbsp;·&nbsp; {city.name} &nbsp;·&nbsp; generated "
        f"{local.strftime('%d %b %Y, %H:%M')} {local.tzname()}", st["sub"]))
    flow.append(Spacer(1, 7))

    # candidate.title is already "<action label> — <target>"; prefixing the
    # action again produced "Stop work - construction site - Stop work -
    # construction site - Metro corridor extension".
    flow.append(Paragraph(f"<b>{candidate.title}</b>", st["h2"]))

    # --- the ask, up top: an inspector should not have to read to page 2 ---
    impact = [
        [f"Averted in {candidate.ward_name} (t+24h)", f"{candidate.ward_averted_ugm3:.2f} µg/m³"],
        ["Averted per person (mean)", f"{candidate.predicted_ugm3_averted:.2f} µg/m³"],
        ["People protected", f"{candidate.population_protected:,}"],
        ["Effort", f"{candidate.effort_units} team{'s' if candidate.effort_units > 1 else ''}"],
        ["Model confidence", f"{candidate.confidence:.2f}"],
        ["ROI score", f"{candidate.roi_score:,.1f}"],
    ]
    # Peak still belongs on the page, just not as a headline number.
    t = Table([[Paragraph(f"<font size=6.5 color='#64748B'>{k.upper()}</font><br/>"
                          f"<font size=11><b>{v}</b></font>", st["cell"]) for k, v in impact[:3]],
               [Paragraph(f"<font size=6.5 color='#64748B'>{k.upper()}</font><br/>"
                          f"<font size=11><b>{v}</b></font>", st["cell"]) for k, v in impact[3:]]],
              colWidths=[W / 3] * 3)
    t.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.5, LINE),
        ("INNERGRID", (0, 0), (-1, -1), 0.4, LINE),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
    ]))
    flow.append(t)
    flow.append(Spacer(1, 4))
    flow.append(Paragraph(
        f"Predicted impact is a Gaussian plume counterfactual (source halted vs. source "
        f"running) under the forecast wind field, for <b>this site alone</b> — not for the "
        f"whole source category, whose ward-level share is given in the reasoning below. "
        f"<b>Averted per person</b> is the population-weighted mean across every ward the "
        f"plume reaches, which is what the ROI multiplies; the ward figure is what "
        f"{candidate.ward_name} itself gains. Both are 24-hour means and sit below the "
        f"modelled peak of {candidate.peak_ugm3_averted:.2f} µg/m³. Confidence combines "
        f"source-attribution confidence with the dispersion model's own (0.8 ceiling).",
        st["small"]))

    # --- where ---
    flow.append(Paragraph("1 · Target location", st["h2"]))
    dist = candidate.distance_km
    flow.append(_kv_table([
        ("Enforcement target", f"{candidate.source_lat:.5f}, {candidate.source_lon:.5f}"),
        ("Affected ward", f"{candidate.ward_name} ({candidate.ward_id})"),
        ("Distance to ward", f"{dist:.1f} km"),
        ("Directions", f'<link href="https://www.google.com/maps/search/?api=1&query='
                       f'{candidate.source_lat:.5f},{candidate.source_lon:.5f}" color="#0EA5E9">'
                       f"Open in Maps</link>"),
    ], st, W))
    flow.append(Spacer(1, 6))

    png = render_map(candidate, ward_geom, rec_lat, rec_lon, wind_dir_from_deg)
    img_buf = io.BytesIO(png)
    iw, ih = Image(io.BytesIO(png))._restrictSize(W, 78 * mm)
    flow.append(Image(img_buf, width=iw, height=ih))
    flow.append(Spacer(1, 8))

    # --- evidence ---
    flow.append(Paragraph("2 · Evidence", st["h2"]))
    if candidate.evidence:
        head = ["#", "Observation", "Location", "Distance", "Observed at", "Source"]
        rows = [[Paragraph(f"<b>{h}</b>", st["cell"]) for h in head]]
        for i, e in enumerate(candidate.evidence[:12], 1):
            ts = getattr(e, "timestamp", None)
            when = "—"
            if ts:
                try:
                    when = pd.Timestamp(ts).tz_convert(city.timezone).strftime("%d %b %H:%M")
                except (ValueError, TypeError):
                    when = str(ts)[:16]
            loc = f"{e.lat:.4f}, {e.lon:.4f}" if getattr(e, "lat", None) else "—"
            d = f"{e.distance_km:.1f} km" if getattr(e, "distance_km", None) is not None else "—"
            rows.append([
                Paragraph(str(i), st["cell"]),
                Paragraph(f"{e.label}<br/><font size=6 color='#64748B'>{e.detail or ''}</font>", st["cell"]),
                Paragraph(loc, st["cell"]),
                Paragraph(d, st["cell"]),
                Paragraph(when, st["cell"]),
                Paragraph(e.source or "—", st["cell"]),
            ])
        et = Table(rows, colWidths=[W * 0.04, W * 0.34, W * 0.16, W * 0.1, W * 0.15, W * 0.21],
                   repeatRows=1)
        et.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
            ("INNERGRID", (0, 0), (-1, -1), 0.35, LINE),
            ("BOX", (0, 0), (-1, -1), 0.5, LINE),
            ("TOPPADDING", (0, 0), (-1, -1), 3.5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3.5),
        ]))
        flow.append(et)
        if len(candidate.evidence) > 12:
            flow.append(Spacer(1, 3))
            flow.append(Paragraph(
                f"Showing 12 of {len(candidate.evidence)} evidence items, strongest first. "
                f"Full set retained in the audit log against this order ID.", st["small"]))
    else:
        flow.append(Paragraph("No discrete evidence items attached.", st["small"]))

    flow.append(Spacer(1, 4))
    flow.append(Paragraph(f"<b>Attribution reasoning.</b> {candidate.rationale}", st["body"]))

    # --- law ---
    flow.append(Paragraph("3 · Regulatory basis", st["h2"]))
    reg = candidate.regulation
    if reg:
        block = [
            Paragraph(f"<b>{reg['title']}</b>", st["body"]),
            Spacer(1, 2),
            Paragraph(f"<i>{reg['instrument']} — {reg['clause']}</i>", st["small"]),
            Spacer(1, 4),
            Paragraph(f'"{reg["text"]}"', st["quote"]),
            Spacer(1, 4),
            Paragraph(f"<b>Citation:</b> {reg['citation']}", st["small"]),
        ]
        if reg.get("penalty_reference"):
            block.append(Paragraph(f"<b>Penalty:</b> {reg['penalty_reference']}", st["small"]))
        block.append(Spacer(1, 3))
        block.append(Paragraph(
            "Abridged restatement for a prototype. Verify against the current CAQM order "
            "at caqm.nic.in before issuing.", st["warn"]))
        bt = Table([[block]], colWidths=[W])
        bt.setStyle(TableStyle([
            ("BOX", (0, 0), (-1, -1), 0.5, LINE),
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FEFCE8")),
            ("LEFTPADDING", (0, 0), (-1, -1), 9),
            ("RIGHTPADDING", (0, 0), (-1, -1), 9),
            ("TOPPADDING", (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ]))
        flow.append(KeepTogether(bt))
    else:
        flow.append(Paragraph(
            "<b>No regulatory clause matched.</b> This order cannot be issued until a legal "
            "basis is identified.", st["warn"]))

    # --- provenance & sign-off ---
    flow.append(Paragraph("4 · Provenance", st["h2"]))
    prov = [
        ("Signal detected", signal_ts.astimezone(local.tzinfo).strftime("%d %b %Y, %H:%M")
         if signal_ts else "—"),
        ("Dossier generated", local.strftime("%d %b %Y, %H:%M")),
    ]
    if signal_ts is not None:
        elapsed = (now - pd.Timestamp(signal_ts)).total_seconds()
        prov.append(("Signal → dossier", f"{int(elapsed // 60)}m {int(elapsed % 60)}s"))
    prov += [
        ("Attribution", "Evidence fusion — NASA FIRMS VIIRS, OpenAQ/CPCB, Open-Meteo winds, "
                        "OSM road network"),
        ("Dispersion", "Gaussian plume, Briggs (1973) rural coefficients, Pasquill-Gifford "
                       "stability from wind &amp; boundary-layer height"),
        ("Emission factors", "Wooster et al. (2005) FRP→fuel; Andreae &amp; Merlet (2001) PM2.5"),
    ]
    if forecast_note:
        prov.append(("Forecast context", forecast_note))
    flow.append(_kv_table(prov, st, W))

    flow.append(Paragraph("5 · Authorisation", st["h2"]))
    flow.append(Paragraph(
        "VAYU recommends; a human authorises. This order is not valid until signed below.",
        st["small"]))
    flow.append(Spacer(1, 10))
    sign = [
        ["Recommended by", "Authorised by", "Executed by"],
        ["VAYU (automated)\nconfidence %.2f" % candidate.confidence, "", ""],
        ["", "", ""],
    ]
    sd = [[Paragraph(f"<font size=6.5 color='#64748B'>{c.upper()}</font>", st["cell"]) for c in sign[0]],
          [Paragraph(sign[1][0].replace("\n", "<br/>"), st["cell"]),
           Paragraph("<br/><br/>Name / Designation", st["small"]),
           Paragraph("<br/><br/>Name / Designation", st["small"])],
          [Paragraph("<br/>Date &amp; time", st["small"]),
           Paragraph("<br/>Signature &amp; date", st["small"]),
           Paragraph("<br/>Signature &amp; date", st["small"])]]
    t = Table(sd, colWidths=[W / 3] * 3, rowHeights=[14, 34, 30])
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOX", (0, 0), (-1, -1), 0.5, LINE),
        ("INNERGRID", (0, 0), (-1, -1), 0.4, LINE),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
    ]))
    flow.append(t)

    flow.append(Spacer(1, 9))
    dt = Table([[Paragraph(DISCLAIMER, st["small"])]], colWidths=[W])
    dt.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#FCA5A5")),
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FEF2F2")),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    flow.append(dt)

    doc.build(flow, onFirstPage=_watermark, onLaterPages=_watermark,
              canvasmaker=_WatermarkCanvas)
    logger.info(f"dossier {candidate.id} -> {path} ({path.stat().st_size / 1024:.0f} KB)")
    return Dossier(order_id=candidate.id, path=path, generated_ts=now)
