"""Health and evaluation metadata (the Methodology page reads these)."""

from __future__ import annotations

import json

from datetime import datetime

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from vayu_core.config import (
    REPO_ROOT,
    clock_override,
    get_settings,
    list_cities,
    set_clock,
)
from vayu_core.db import read_conn

from ..schemas import HealthOut

router = APIRouter(tags=["meta"])

# Notable episodes — quick-jump shortcuts for the date picker, not a restriction.
# The picker spans the whole archive; these are just the hours worth landing on,
# measured (not synthetic) and spanning the arc of a Delhi winter: a clean day,
# the season's first uptick, the crisis building, the flagship severe episode,
# and the season's worst hour.
NOTABLE_DATES: dict[str, list[dict]] = {
    "delhi": [
        {"at": "2025-09-03T17:00:00Z", "label": "Clean day", "aqi": 55, "category": "Good"},
        {"at": "2025-09-17T17:00:00Z", "label": "Early-season uptick", "aqi": 107, "category": "Moderate"},
        {"at": "2025-10-24T17:00:00Z", "label": "Crisis building", "aqi": 337, "category": "Very Poor"},
        {"at": "2025-11-03T06:00:00Z", "label": "Flagship severe episode", "aqi": 373, "category": "Very Poor"},
        {"at": "2025-11-24T00:00:00Z", "label": "Peak of the season", "aqi": 405, "category": "Severe"},
    ],
}


class ClockIn(BaseModel):
    as_of: datetime | None = None  # None clears the pin (back to the default instant)


def _clock_state() -> dict:
    """The app clock plus the archive window the picker may select within.

    VAYU reads a fixed historical archive (CPCB/satellite records through Nov
    2025) — there is no live-fetch path, so the selectable range is exactly the
    data on disk. Everything downstream keys off `settings.now()`.
    """
    settings = get_settings()
    pinned = clock_override()
    with read_conn() as con:
        row = con.execute("SELECT min(ts), max(ts) FROM measurements").fetchone()
    lo, hi = (row or (None, None))
    return {
        "now": settings.now(),
        "source": "override" if pinned is not None else "archive",
        "pinned": pinned is not None,
        "data_min": lo,
        "data_max": hi,
        "max_selectable": hi,
    }


@router.get("/clock")
def get_clock() -> dict:
    """The app's effective clock + the date range the picker can select within."""
    return _clock_state()


@router.get("/notable-dates")
def get_notable_dates(city_id: str = "delhi") -> dict:
    """Quick-jump episodes for the date picker — see NOTABLE_DATES."""
    return {"city": city_id, "dates": NOTABLE_DATES.get(city_id, [])}


@router.post("/clock")
def post_clock(body: ClockIn) -> dict:
    """Pin the whole app to `as_of` (any hour in the archive), or clear the pin.

    Every read surface keys off `settings.now()`, so this moves the nowcast,
    forecast horizons, alerts, GRAP stage and ROI together to the chosen instant.
    Forecasts for that hour are scored on demand on first request.
    """
    set_clock(body.as_of)
    return _clock_state()


@router.get("/health", response_model=HealthOut)
def health() -> HealthOut:
    settings = get_settings()
    try:
        with read_conn() as con:
            wards = con.execute("SELECT count(*) FROM wards").fetchone()[0]
            meas = con.execute("SELECT count(*) FROM measurements").fetchone()[0]
    except Exception as exc:  # noqa: BLE001
        return HealthOut(
            status="degraded",
            demo_mode=settings.demo_mode,
            now=settings.now(),
            cities=[c.id for c in list_cities()],
            seeded=False,
            detail=f"database unavailable: {exc}",
        )

    seeded = wards > 0 and meas > 0
    return HealthOut(
        status="ok" if seeded else "degraded",
        demo_mode=settings.demo_mode,
        now=settings.now(),
        cities=[c.id for c in list_cities()],
        seeded=seeded,
        detail="" if seeded else "no data yet — run `make seed`",
    )


@router.get("/meta/evaluation")
def evaluation() -> dict:
    """Backtest metrics for the Methodology page.

    Generated by `make backtest` in Phase 2; until then this reports honestly
    that it has not been run rather than shipping placeholder numbers.
    """
    path = REPO_ROOT / "docs" / "evaluation.json"
    if not path.exists():
        raise HTTPException(
            status_code=404,
            detail="Backtest has not been run yet — `make backtest` generates docs/evaluation.md (Phase 2).",
        )
    return json.loads(path.read_text())
